name: open-webui
services:
    open-webui:
        container_name: open-webui
        ports:
            - 3020:8080
        environment:
            - OLLAMA_BASE_URL=http://192.168.0.2:11434
            - RAG_EMBEDDING_MODEL_AUTO_UPDATE=True
            - HF_ENDPOINT=https://hf-mirror.com
        volumes:
            - /data/docker/open-webui:/app/backend/data
        restart: always
        image: ghcr.io/open-webui/open-webui:main
